# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Universal Presenter Remote' do
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'Universal Presenter RemoteTests' do

end

target 'Universal Presenter Remote WatchKit Extension' do

end

target 'Universal Presenter Remote WatchKit App' do

end

