# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Universal Presenter Remote' do
  pod 'Google/Analytics'
end

target 'Universal Presenter RemoteTests' do

end

target 'Universal Presenter Remote WatchKit Extension' do

end

target 'Universal Presenter Remote WatchKit App' do

end

