//
//  InstructionsView.swift
//  Universal Presenter Remote
//
//  Paged, step-by-step pairing instructions.
//

import SwiftUI

private struct InstructionStep: Identifiable {
    let id: Int
    let image: String
    let title: String
    let body: String
}

struct InstructionsView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var index = 0

    private let steps: [InstructionStep] = [
        InstructionStep(
            id: 1,
            image: "Instruction-1",
            title: "Open the control software",
            body: "Install and open the UPR control software on the computer you'll be presenting from, and make sure it's connected to the internet."
        ),
        InstructionStep(
            id: 2,
            image: "Instruction-2",
            title: "Enter your token",
            body: "Enter the token generated by this App (the remote) into the control software and click begin. You should now recieve a notification on the remote, letting you know that you are ready to present."
        ),
        InstructionStep(
            id: 3,
            image: "Instruction-3",
            title: "Start presenting",
            body: "Tap Begin on the remote once it's connected. Use Next, Previous, and Play / pause media to control your presentation."
        )
    ]

    var body: some View {
        NavigationStack {
            VStack(spacing: 0) {
                TabView(selection: $index) {
                    ForEach(steps.indices, id: \.self) { i in
                        stepView(steps[i])
                            .tag(i)
                    }
                }
                .tabViewStyle(.page(indexDisplayMode: .never))

                Button(index == steps.count - 1 ? "Done" : "Next") {
                    if index == steps.count - 1 {
                        dismiss()
                    } else {
                        withAnimation { index += 1 }
                    }
                }
                .buttonStyle(PrimaryButtonStyle())
                .padding(20)
            }
            .navigationTitle("Instructions")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    if index > 0 {
                        Button {
                            withAnimation { index -= 1 }
                        } label: {
                            Image(systemName: "chevron.left")
                        }
                    }
                }
                ToolbarItem(placement: .topBarTrailing) {
                    Button {
                        dismiss()
                    } label: {
                        Image(systemName: "xmark")
                    }
                }
            }
        }
    }

    private func stepView(_ step: InstructionStep) -> some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {
                Image(step.image)
                    .resizable()
                    .scaledToFit()
                    .frame(maxWidth: .infinity)
                    .frame(maxHeight: 240)
                    .padding(24)
                    .background(Color.uprPresentBackground,
                                in: RoundedRectangle(cornerRadius: 20))

                HStack(spacing: 12) {
                    Text("\(step.id)")
                        .font(.system(size: 16, weight: .bold))
                        .foregroundStyle(.white)
                        .frame(width: 34, height: 34)
                        .background(Color.uprPrimary, in: Circle())
                    Text(step.title)
                        .font(.uprTitle(24))
                }

                Text(step.body)
                    .font(.system(size: 16))
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
            .padding(24)
        }
    }
}

#Preview {
    InstructionsView()
}
